### ISSUE TITLE
ElementName not exposed

### ISSUE THREAD

**Issue by EdVanDance** [DanielT/autosar-data-py#5]
Hello 🙂

It seems to me that, although `ElemenName` is mentioned in the `pyi`, it is not exposed in `lib.rs`.

I stumbled across this because I was trying to extract all Elements of a specific type. I was hoping there is a "better" way than using the corresponding XML Tag as string to check against `Element.element_name`.

Regards,
Ed

**Comment by DanielT** [comment]
I changed ElementName to be a type alias for str quite a while ago.

Initially I had it as an enum, which is what you seem to be looking for, but the ergonomics of using it that way seemed questionable. Just comparing the XML tag seemed to be a better fit in Python.

Do you have performance problems that you think using enums would solve?

I suppose it would be possible to allow both notations, i.e String and Enum - I just didn't know how to do that when I had just started using pyo3.

**Comment by EdVanDance** [comment]
Oh now I get it. My bad.

It popped up as an auto complete suggestion when importing from `autosar_data`, so I thought something went wrong. But yeah, makes sense. There is probably no real benefit without intuitive clustering/grouping.

It's funny to me that you mention performance, coming from a heavy artop based eclipse tooling this feels soooo nice 😄 Especially getting a merged model out of the box is awesome. Kudos to you.

I'm closing this. Thank you for the feedback 👍
